"""
backfill_transactions.py
─────────────────────────
The 48 customers generated by generate_customers.py (CUST200-CUST247) only ever
got EMI loan-repayment debit transactions — no salary/income credits, no UPI or
bill payment debits. That makes every one of those accounts look like "all
debits" in the operations UI, which isn't realistic.

This script adds, for each of those accounts, a monthly income credit (salary,
pension, business/freelance income, or family allowance for students) plus a
couple of small recurring expense debits (bill payment, UPI), spanning the same
date range as the account's existing EMI history. NPA-classified loans get
irregular/reduced income credits to reflect financial distress consistent with
their default status.

8 of the 48 customers (the deliberately-defaulted set in generate_customers.py)
have ZERO transactions at all — no EMI debits either, since
sync_bank_loan_metrics.py's default rule treats 3 consecutive missing EMI
months as a default signal. For those, this script still adds income/expense
transactions (using the loan's disbursed date as the window start) so the
account isn't completely empty, but deliberately adds no EMI-payment entries,
preserving the missing-EMI default signal.

Existing transactions (EMI debits, and the two hand-seeded customers CUST004 /
CUST046) are left untouched. balance_after is left NULL and accounts.balance is
not recalculated, matching the convention already used for the bulk-generated
EMI transactions.

Run:
    python operations/scripts/backfill_transactions.py
"""

import os
import sqlite3
import random
from datetime import date, datetime

random.seed(7)
DB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'bank.db')

EMPLOYER_DESC = {
    'GOVT':          ('Deposit', '[INCOME] Salary - Monthly salary credit from {employer}'),
    'SALARIED':      ('Deposit', '[INCOME] Salary - Monthly salary credit from {employer}'),
    'RETIRED':       ('Deposit', '[INCOME] Pension - Monthly pension credit from {employer}'),
    'SELF_EMPLOYED': ('Deposit', '[INCOME] Business Income - Monthly professional income credit'),
    'BUSINESS':      ('Deposit', '[INCOME] Business Income - Monthly business revenue deposit'),
    'FREELANCE':     ('Deposit', '[INCOME] Freelance Income - Monthly freelance project payment received'),
    'STUDENT':       ('Deposit', '[INCOME] Family Support - Monthly allowance received from family'),
}

STUDENT_ALLOWANCE_RANGE = (8000, 15000)


def month_range(start_str, end_str):
    """Inclusive list of (year, month) between two YYYY-MM-DD date strings."""
    start = datetime.strptime(start_str, '%Y-%m-%d').date()
    end   = datetime.strptime(end_str,   '%Y-%m-%d').date()
    y, m = start.year, start.month
    months = []
    while (y, m) <= (end.year, end.month):
        months.append((y, m))
        m += 1
        if m > 12:
            m, y = 1, y + 1
    return months


def main():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()

    cursor.execute("""
        SELECT c.id AS cid, c.bank_id, k.employment_type, k.annual_income,
               k.employer_name, a.id AS aid, l.loan_classification, l.disbursed
        FROM customers c
        JOIN customer_kyc k ON k.cid = c.id
        JOIN accounts a ON a.cid = c.id
        JOIN loans l ON l.cid = c.id
        WHERE c.id NOT IN (
            SELECT a2.cid FROM accounts a2
            JOIN transactions t ON t.aid = a2.id
            WHERE t.type != 'Debit'
        )
        ORDER BY c.id
    """)
    customers = cursor.fetchall()
    print("Customers to backfill: {}".format(len(customers)))

    cursor.execute("SELECT MAX(CAST(SUBSTR(id, 7) AS INTEGER)) FROM transactions WHERE id LIKE 'TX-BF-%'")
    next_seq = (cursor.fetchone()[0] or 0) + 1

    def next_id():
        nonlocal next_seq
        tid = 'TX-BF-{:06d}'.format(next_seq)
        next_seq += 1
        return tid

    total_inserted = 0

    for cust in customers:
        cid, bank_id, emp_type, annual_income, employer_name, aid, classification, disbursed = (
            cust['cid'], cust['bank_id'], cust['employment_type'], cust['annual_income'],
            cust['employer_name'], cust['aid'], cust['loan_classification'], cust['disbursed']
        )
        is_npa = classification in ('NPA', 'Doubtful', 'Loss')

        cursor.execute("SELECT MIN(date), MAX(date) FROM transactions WHERE aid = ?", (aid,))
        row = cursor.fetchone()
        if row and row[0]:
            window_start, window_end = row[0], row[1]
        else:
            # No transactions at all (deliberately-defaulted accounts) - use the
            # loan's disbursed date through today as the income/expense window.
            window_start, window_end = disbursed, date.today().isoformat()

        if emp_type == 'STUDENT':
            monthly_income = random.randint(*STUDENT_ALLOWANCE_RANGE)
        else:
            monthly_income = round((annual_income or 0) / 12, 2)
        if monthly_income <= 0:
            continue

        _, desc_template = EMPLOYER_DESC.get(emp_type, EMPLOYER_DESC['SALARIED'])
        desc = desc_template.format(employer=employer_name or 'employer')

        rows_to_insert = []

        for (y, m) in month_range(window_start, window_end):
            if is_npa and random.random() < 0.3:
                continue  # missed/irregular income month - financial distress

            variance = random.uniform(0.9, 1.05) if not is_npa else random.uniform(0.55, 0.9)
            amount = round(monthly_income * variance, 2)

            rows_to_insert.append({
                'id': next_id(), 'bank_id': bank_id, 'aid': aid,
                'date': date(y, m, 1).isoformat(), 'time': '09:00:00',
                'type': 'Deposit', 'amount': amount, 'balance_after': None,
                'desc': desc
            })

            # Small recurring expenses in months where income landed
            bill_amt = round(monthly_income * random.uniform(0.06, 0.12), 2)
            rows_to_insert.append({
                'id': next_id(), 'bank_id': bank_id, 'aid': aid,
                'date': date(y, m, 12).isoformat(), 'time': '11:00:00',
                'type': 'Bill Payment', 'amount': bill_amt, 'balance_after': None,
                'desc': '[UTILITIES] Bill Payment - Monthly electricity, internet and water bill'
            })

            upi_amt = round(monthly_income * random.uniform(0.08, 0.16), 2)
            rows_to_insert.append({
                'id': next_id(), 'bank_id': bank_id, 'aid': aid,
                'date': date(y, m, 20).isoformat(), 'time': '19:30:00',
                'type': 'UPI Payment', 'amount': upi_amt, 'balance_after': None,
                'desc': '[LIFESTYLE] UPI Payment - Groceries and daily household expenses'
            })

        cursor.executemany("""
            INSERT INTO transactions (id, bank_id, aid, date, time, type, amount, balance_after, desc)
            VALUES (:id, :bank_id, :aid, :date, :time, :type, :amount, :balance_after, :desc)
        """, rows_to_insert)

        total_inserted += len(rows_to_insert)
        print("  {} ({}, {}{}) -> +{} transactions".format(
            cid, emp_type, 'NPA, ' if is_npa else '', aid, len(rows_to_insert)))

    conn.commit()
    conn.close()
    print("\nDone. Inserted {} transactions across {} customers.".format(total_inserted, len(customers)))


if __name__ == '__main__':
    main()
